/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package edu.isu.cs.cs2263;
import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;


import java.util.List;
import java.util.Vector;

public class App extends Application implements EventHandler<ActionEvent> {
 public static Vector<Course> vector = new Vector<>();
   // Department department = new Department();
   // public list<Department> department;
   Button button = new Button();
   ComboBox<String> comboBox;
   public App(){
       super();


   }

    public static void main(String[] args) {
        Application.launch();
    }
    public void start(Stage primaryStage) throws Exception {
        primaryStage.setTitle("Department View");

        comboBox = new ComboBox<>();
        comboBox.getItems().addAll(
                " Computer Science",
                            "Mathematics ",
                            " Physics",
                              "Botany ",
                              " Zoology"
        );

        BorderPane main = new BorderPane();
        //main.setLeft(comboBox);
        comboBox.setPromptText("Select a department from the departments listed below ");

        TextField name = new TextField();
        TextField number = new TextField();
        TextField credits = new TextField();



        //Button section for button called Enter

        Button enterdata = new Button("Enter Course Data");
        enterdata.setOnAction(e ->{

      // vector.add(new Course(name.getText(), Integer.parseInt(number.getText()), Integer.parseInt(credits.getText())));
           // out.setText(name.getText());
            //System.out.println(name.getText());

                }
            );





        // Button section for button called load data
        BorderPane dwnpane = new BorderPane();
        Button loadData = new Button(" Load Data");

        loadData.setOnAction(event -> {
        //    System.out.println(vector);
        });
        dwnpane.setRight(loadData);
        main.setBottom(dwnpane);



        // VBox layout
        VBox layout = new VBox(10);
        layout.getChildren().addAll( comboBox, enterdata, name, number, credits);
        main.setCenter(layout);



        // scene Builder
        Scene scene = new Scene(main,  800, 500);
        primaryStage.setScene(scene);

        primaryStage.show();
    }

    @Override
    public void handle(ActionEvent event) {


    }
}
